name: Images

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-26.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      pairs: ${{ steps.set-matrix.outputs.pairs }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      -
        id: set-matrix
        run: |
          matrix=$(jq -c '{"otp" : .otp | keys}' versions.json)
          echo "Matrix: $matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          pairs=$(jq -c '{"include": [ .otp | to_entries[] | .key as $otp | (.value.elixir // [])[] | {otp: $otp, elixir: .} ]}' versions.json)
          echo "Pairs: $pairs"
          echo "pairs=$pairs" >> $GITHUB_OUTPUT

  build:
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/build-image.yaml
    with:
      otp-version: ${{ matrix.otp }}
    secrets: inherit

  build-elixir:
    needs: [matrix, build]
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.pairs) }}
      fail-fast: false
    uses: ./.github/workflows/build-elixir.yaml
    with:
      otp-version: ${{ matrix.otp }}
      elixir-version: ${{ matrix.elixir }}
    secrets: inherit
